-- ============================================================
-- CƠ SỞ DỮ LIỆU CHUẨN SUPABASE (POSTGRESQL) - KHẮC PHỤC LỖI COLUMNS
-- Dự án: WEB THCS ĐỒNG TÂN
-- Hướng dẫn: Copy toàn bộ nội dung file này vào Supabase SQL Editor và bấm RUN.
-- ============================================================

-- 1. XÓA BẢNG CŨ NẾU ĐÃ TỒN TẠI ĐỂ ĐẢM BẢO TẠO MỚI CHÍNH XÁC 100%
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS utilities CASCADE;
DROP TABLE IF EXISTS administrative_documents CASCADE;
DROP TABLE IF EXISTS announcements CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS site_settings CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. HÀM TỰ ĐỘNG CẬP NHẬT THỜI GIAN UPDATED_AT (PostgreSQL Trigger)
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3. BẢNG NGƯỜI DÙNG & PHÂN QUYỀN (users)
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) DEFAULT 'TEACHER' CHECK (role IN ('ADMIN', 'BGH', 'TEACHER', 'EDITOR')),
    email VARCHAR(100),
    avatar VARCHAR(255),
    status VARCHAR(20) DEFAULT 'APPROVED' CHECK (status IN ('APPROVED', 'PENDING_APPROVAL', 'REJECTED')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BẢNG CẤU HÌNH TRANG BÌA & LIÊN KẾT NHANH (site_settings)
CREATE TABLE site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER trg_site_settings_updated_at
BEFORE UPDATE ON site_settings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 5. BẢNG DANH MỤC (categories)
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    type VARCHAR(20) DEFAULT 'NEWS' CHECK (type IN ('NEWS', 'UTILITY', 'DOC')),
    order_index INT DEFAULT 0
);

-- 6. BẢNG BÀI VIẾT TIN TỨC & SỰ KIỆN (posts)
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    excerpt TEXT,
    content TEXT,
    thumbnail VARCHAR(255),
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    author_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    view_count INT DEFAULT 0,
    is_featured INT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'PUBLISHED' CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TRIGGER trg_posts_updated_at
BEFORE UPDATE ON posts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 7. BẢNG THÔNG BÁO MỐC THỜI GIAN (announcements)
CREATE TABLE announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    month_label VARCHAR(10) NOT NULL,
    day_label VARCHAR(10) NOT NULL,
    target_url VARCHAR(255) DEFAULT '#',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. BẢNG VĂN BẢN CHỈ ĐẠO & HÀNH CHÍNH (administrative_documents)
CREATE TABLE administrative_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_number VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(100) DEFAULT 'VBHC',
    file_url VARCHAR(255),
    published_date DATE DEFAULT CURRENT_DATE,
    issuing_authority VARCHAR(150),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. BẢNG DANH MỤC TIỆN ÍCH SIDEBAR (utilities)
CREATE TABLE utilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    icon_type VARCHAR(50) NOT NULL,
    target_url VARCHAR(255) DEFAULT '#',
    order_index INT DEFAULT 0,
    is_active INT DEFAULT 1
);

-- 10. BẢNG NHẬT KÝ VẾT & XUẤT BẢN (audit_logs)
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    user_name VARCHAR(100),
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT,
    details TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- NẠP DỮ LIỆU MẪU KHỞI TẠO (SEED DATA)
-- ============================================================

-- 1. Nạp Tài Khoản Mẫu (Admin & Giáo viên)
INSERT INTO users (username, password, full_name, role, email, status)
VALUES
('admin', 'admin123', 'Ban Giám Hiệu Admin', 'ADMIN', 'admin@thcsdongtan.huulung.langson.edu.vn', 'APPROVED'),
('giaovien1', 'gv123', 'Nguyễn Văn A (Giáo viên)', 'TEACHER', 'nguyenvana@thcsdongtan.edu.vn', 'APPROVED'),
('teacher_pending', '123456', 'Trần Thị B (Giáo viên Đăng ký)', 'TEACHER', 'tranthib@thcsdongtan.edu.vn', 'PENDING_APPROVAL');

-- 2. Nạp Cấu Hình Trang Bìa & Khối Chủ Quản (Ảnh 2)
INSERT INTO site_settings (setting_key, setting_value)
VALUES
('agency_title', 'ỦY BAN NHÂN DÂN XÃ HỮU LŨNG - TỈNH LẠNG SƠN'),
('school_name', 'TRƯỜNG THCS ĐỒNG TÂN'),
('address', 'Xã Hữu Lũng - Tỉnh Lạng Sơn'),
('phone', '(0205) 3885.6789'),
('email', 'thcsdongtan.huulung@langson.edu.vn'),
('quick_links', '[{"id":1,"title":"Giới thiệu nhà trường","url":"#gioi-thieu"},{"id":2,"title":"Tin tức - Sự kiện nổi bật","url":"#tin-tuc"},{"id":3,"title":"Văn bản chỉ đạo & Quy chế","url":"#van-ban"},{"id":4,"title":"Kho Tài nguyên & Đề thi","url":"#tai-nguyen"},{"id":5,"title":"Lịch công tác tuần","url":"#lich-cong-tac"}]');

-- 3. Nạp Danh Mục Tiện Ích Sidebar
INSERT INTO utilities (title, icon_type, target_url, order_index)
VALUES
('Email phòng GD&ĐT', 'email', 'mailto:phonggddt@hanoi.gov.vn', 1),
('Lịch công tác', 'calendar', '#lich-cong-tac', 2),
('Tài nguyên công nghệ', 'tech', '#tai-nguyen-cong-nghe', 3),
('Cơ sở dữ liệu THPT/THCS', 'database', '#csdl-thpt', 4),
('Công bố trực tuyến VBHC', 'doc', '#cong-bo-vbhc', 5),
('Thủ tục hành chính', 'procedure', '#thu-tuc-hanh-chinh', 6);

-- 4. Nạp Thông Báo Mốc Lịch
INSERT INTO announcements (title, content, month_label, day_label, target_url)
VALUES
('Sở Giáo dục và Đào tạo tổ chức tập huấn chuyên môn đầu năm học', 'Tập huấn chuyên môn nâng cao phương pháp giảng dạy...', 'Th.11', '19', '#'),
('Các trường học Tam Kỳ tổ chức tham quan về nguồn nhân các ngày lễ lớn tháng 4', 'Tổ chức hoạt động ngoại khóa tìm hiểu lịch sử...', 'Th.11', '19', '#'),
('Sở GDĐT tổ chức tập huấn mô hình trường học mới đối với lớp 3 cấp TH', 'Ứng dụng công nghệ thông tin trong dạy và học...', 'Th.11', '19', '#');

-- 5. Nạp Bài Viết Tin Tức Nổi Bật
INSERT INTO posts (title, slug, excerpt, content, thumbnail, is_featured, status, view_count)
VALUES
('Lễ kết nạp Đảng viên mới cho cán bộ giáo viên THCS Đồng Tân', 'le-ket-nap-dang-vien-moi-cho-can-bo-giao-vien', 'Vào lúc 14 giờ 00, Chi bộ trường THCS Đồng Tân đã long trọng tổ chức Lễ kết nạp Đảng viên cho giáo viên ưu tú...', 'Nội dung chi tiết buổi lễ kết nạp...', 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&q=80', 1, 'PUBLISHED', 342),
('Bộ GD&ĐT ban hành Chỉ thị về nhiệm vụ trọng tâm năm học 2026 - 2027', 'bo-gd-dt-ban-hanh-chi-thi-nhiem-vu-trong-tam', 'Tập trung nâng cao chất lượng giáo dục toàn diện, đẩy mạnh chuyển đổi số trong công tác quản lý...', 'Nội dung chi tiết chỉ thị...', 'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=80', 0, 'PUBLISHED', 189);

-- 6. Nạp Văn Bản Hành Chính
INSERT INTO administrative_documents (doc_number, title, category, published_date)
VALUES
('232/2026/NĐ-CP', 'Nghị định quy định về vị trí việc làm của viên chức', 'Nghị định', '2026-06-26'),
('124/HD-SGDĐT', 'Hướng dẫn thực hiện nhiệm vụ ứng dụng CNTT năm học 2025-2026', 'Hướng dẫn', '2026-09-01');

-- ============================================================
-- BẬT SUPABASE ROW LEVEL SECURITY (RLS) - ĐỌC CÔNG KHAI
-- ============================================================
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE administrative_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE utilities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Posts" ON posts FOR SELECT USING (true);
CREATE POLICY "Public Read Site Settings" ON site_settings FOR SELECT USING (true);
CREATE POLICY "Public Read Announcements" ON announcements FOR SELECT USING (true);
CREATE POLICY "Public Read Documents" ON administrative_documents FOR SELECT USING (true);
CREATE POLICY "Public Read Utilities" ON utilities FOR SELECT USING (true);
